name: Build and Auto-Commit Dist

on:
  push:
    branches:
      - master       # Production
      - develop      # Development
      - 'feature/**' # Feature branches
      - 'hotfix/**'  # Hotfix branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: üîÑ Cloning the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false  # –û—Ç–∫–ª—é—á–∞–µ–º —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—É—é –∞—É—Ç–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ü–∏—é

      - name: üõ† Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: üì¶ Installing dependencies
        run: npm ci

      - name: üî® Define environment and build project
        run: |
          if [[ $GITHUB_REF == "refs/heads/master" ]]; then
            export NODE_ENV=production
          else
            export NODE_ENV=development
          fi
          echo "NODE_ENV=$NODE_ENV"
          npm run build

      - name: üì§ Auto commit `dist/`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/dist/
          git commit -m "feat: Automatic dist creation for $NODE_ENV" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:${GITHUB_REF#refs/heads/}
